### ISSUE TITLE
Syntax error: redirection unexpected

### ISSUE THREAD

**Issue by garret** [Aztic/polybar-protonvpn-status#1]
Hi, I tried to install your polybar module after I renamed it to `protonvpn-cli` and chmod it. However, I get the following error when I try to launch your script: 
```
➜  ~ .config/polybar/scripts/protonvpn-cli
.config/polybar/scripts/protonvpn-cli: 13: Syntax error: redirection unexpected
➜  ~
```
I have `protonvpn-cli` installed
```
➜  ~ protonvpn -v
ProtonVPN-CLI v2.2.4
➜  ~
```
Do you know what I am doing wrong?

**Comment by Aztic** [comment]
You need to do either of these options:
- Run it with bash instead of sh.
- add `#!/usr/bin/env bash` at the top of the script to always run with bash even doing `./script`

Or just make a pull or copy the content of the script. Added the line of bash at the top.

**Comment by garret** [comment]
For the moment I just reverted to `bash` just to see if it works and I get this continuous error loop (which I have to stop with CTRL+C): 
```
[garret@void ~]$ .config/polybar/scripts/protonvpn-cli
hostname: invalid option -- 'I'
Try 'hostname --help' for more information.
Disconnected ()
hostname: invalid option -- 'I'
Try 'hostname --help' for more information.
Disconnected ()
hostname: invalid option -- 'I'
Try 'hostname --help' for more information.
Disconnected ()
hostname: invalid option -- 'I'
Try 'hostname --help' for more information.
Disconnected ()
hostname: invalid option -- 'I'
Try 'hostname --help' for more information.
Disconnected ()
^C[garret@void ~]$
```

**Comment by Aztic** [comment]
I'm not too familiar with the differences of the `hostname` command in different distributions. Looks like `hostname -I` is not a valid command in yours. I've only tested this on OpenSuse Tumbleweed and Ubuntu 20.04.

In Ubuntu, for example, these are the available flags
```
Program options:
    -a, --alias            alias names
    -A, --all-fqdns        all long host names (FQDNs)
    -b, --boot             set default hostname if none available
    -d, --domain           DNS domain name
    -f, --fqdn, --long     long host name (FQDN)
    -F, --file             read host name or NIS domain name from given file
    -i, --ip-address       addresses for the host name
    -I, --all-ip-addresses all addresses for the host
    -s, --short            short host name
    -y, --yp, --nis        NIS/YP domain name
```
And the `-I` flag is the one being used there.

**Comment by garret** [comment]
It seems I don't have such options and giving `hostname --help` does not help :/
```
[garret@void ~]$ hostname --help
Usage: hostname [NAME]
  or:  hostname OPTION
Print or set the hostname of the current system.

      --help     display this help and exit
      --version  output version information and exit

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Full documentation <https://www.gnu.org/software/coreutils/hostname>
or available locally via: info '(coreutils) hostname invocation'
[garret@void ~]$
```

I cannot find a command to see which options I have available (I am using Void Linux).

**Comment by Aztic** [comment]
:thinking: Unfortunately, i can't help you there since i haven't used Void Linux. If you can find a command that replaces `hostname -I` ( the expected output is the ip address in you local network, for example: `192.168.0.100` ), then you should be able to change it and run the script without problems.

If you don't want that part, you can always choose to always display the output of the other option.
Basically: the `if` part display your local network IP, and the `else`, the current ip that the `protonvpn status` gives you. Be aware that, if you are not connected to the vpn, this will be your public IP.

So, to put it simple:
- Delete `local_addr=$(hostname -I | sed 's/^[ \t]*//;s/[ \t]*$//' | cut -d' ' -f1);`
- Replace
```
    if [ $t -eq 0 ]; then
        echo "$current_status ($local_addr) $current_server";
    else
        echo "$current_status ($current_proton_ip) $current_server";
    fi
```
with
```
       echo "$current_status ($current_proton_ip) $current_server";
```
And you'll not need the output of `hostname -I`, and your current public ip / ip from the vpn will display there.
